### ISSUE TITLE
When using the environment variable EDGE_PORT it is still using the default port of 4566 to connect

### ISSUE THREAD

**Issue by JackInTheBoxBen** [localstack/awscli-local#73]
When using the environment variable EDGE_PORT I get the default port setting even though it is set to a different port.

Error Message:
Could not connect to the endpoint URL: "http://microk8s-vm.mshome.net:4566/"

>set EDGE_PORT
EDGE_PORT=31566

**Comment by whummer** [comment]
Thanks for reporting @JackInTheBoxBen . We have made some changes in how the target endpoint can be configured a while back, and `EDGE_PORT` config has been depcecated. Unfortunately, this hadn't been reflected in our docs yet - we have now updated the README of this repo. 👍 

The new recommended way is to use the `AWS_ENDPOINT_URL` configuration variable, so in your case this wlud be
```
AWS_ENDPOINT_URL=http://microk8s-vm.mshome.net:31566"
```

Hope that helps. Please let us know if it works or if the problem persists. Thanks!

**Comment by JackInTheBoxBen** [comment]
Thank you for the help!
I am still getting the error when using the other environment variable:

>set AWS_ENDPOINT_URL="http://microk8s-vm.mshome.net:31566"

C:\Users\pierceb>awslocal sqs list-queues

Could not connect to the endpoint URL: "http://localhost:4566/"

Perhaps I have an older version? How can I tell?

**Comment by whummer** [comment]
Thanks for the update @JackInTheBoxBen - can you please also try updating the `localstack-client` package (which `awslocal` depends on):
```
pip install --upgrade awscli-local[ver1] localstack-client
```

**Comment by JackInTheBoxBen** [comment]
The upgrade did the trick. Thank you again.
